// 项目数据
export const projects = [
      {
            title: '悟创物联',
            description: '使用Vue + Springboot的物联网平台，实现设备管理、数据采集、告警管理、用户管理、角色管理、权限管理、日志管理、系统管理等功能。',
            imageUrl: '/projects/big.gif',
            color: 'from-blue-500 to-purple-500',
            state: '已上线',
            tags: ['Vue', 'Springboot', 'IoT'],
            projectLink: 'https://example.com/project1',
            githubLink: 'https://github.com/example/project1',
      },
      {
            title: '判题鸭',
            description: '基于Vue + Springboot的AI在线判题系统，支持多种编程语言，多种题型，多种难度，多种评测方式，多种评测环境，多种评测数据，多种评测结果，多种评测报告，多种评测分析。',
            imageUrl: '/projects/ya.jpg',
            color: 'from-purple-500 to-pink-500',
            state: '已上线',
            tags: ['Vue', 'Springboot', 'AI'],
            projectLink: 'https://example.com/project2',
            githubLink: 'https://github.com/example/project2',
      },
      {
            title: 'API开放平台',
            description: '基于React + Springboot的API开放平台，支持多种API类型，多种API管理，多种API调用，多种API测试，多种API文档，多种API监控，多种API告警，多种API分析。',
            imageUrl: '/placeholder.svg?height=300&width=400',
            color: 'from-indigo-500 to-blue-500',
            state: '已上线',
            tags: ['React', 'Springboot', 'API'],
            projectLink: 'https://example.com/project3',
            githubLink: 'https://github.com/example/project3',
      },
      {
            title: 'AI多模态MCP交流平台',
            description: '基于Vercel AI SDK + SpringAI 的AI多模态MCP交流平台，支持多种AI模型，多种AI功能，多种AI应用，多种AI管理，多种AI监控，多种AI告警，多种AI分析。',
            imageUrl: '/placeholder.svg?height=300&width=400',
            color: 'from-red-500 to-orange-500',
            state: '已上线',
            tags: ['Next.js', 'SpringAI', 'AI'],
            projectLink: 'https://example.com/project4',
            githubLink: 'https://github.com/example/project4',
      },
      {
            title: 'IC Studio 官网',
            description: '如你所见，我们的官网由 React 18 + Next.js 15 开发，包含GSAP，motion，three等多种动画库，包含资源库，展示等多种功能',
            imageUrl: '/logo/logo-t.png',
            color: 'from-green-500 to-lime-500',
            state: '已上线',
            tags: ['React', 'Next.js', 'GSAP'],
            projectLink: 'https://example.com/project5',
            githubLink: 'https://github.com/example/project5',
      },
      {
            title: 'Loome:织',
            description: '多平台强大的多AI多模态视频编辑器，目前处于研发中',
            imageUrl: '/placeholder.svg?height=300&width=400',
            color: 'from-orange-500 to-yellow-500',
            state: '研发中',
            tags: ['Tauri', 'React', 'AI'],
            projectLink: 'https://example.com/project6',
            githubLink: 'https://github.com/example/project6',
      }
];
